### ISSUE TITLE
Panic parsing terminfo

### ISSUE THREAD

**Issue by riquito** [alacritty/vtebench#8]
vtebench panic while trying to run a benchmark, apparently parsing terminfo.
The version used is current master at 300768f39d1cb34c958aaff54c4356faeaaeafee
Here follows system info and backtrace. I attached the terminfo file and the output of strace

```
# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 28 (Twenty Eight)
Release:        28
Codename:       TwentyEight
```

```
RUST_BACKTRACE=1 ./target/debug/vtebench -b 50000000 -w $(tput cols) -h $(tput lines) scrolling-in-region --lines-from-bottom 1
```

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Terminfo(Parse)', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  11: vtebench::main
             at src/main.rs:43
  12: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  13: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  15: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  16: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  17: main
  18: __libc_start_main
  19: _start
```

[strace_output.txt](https://github.com/jwilm/vtebench/files/2056932/strace_output.txt)
[terminfo.zip](https://github.com/jwilm/vtebench/files/2056933/terminfo.zip)

**Comment by chrisduerr** [comment]
I'm having a similar issue and this is probably not the fault of vtebench but rather an issue with terminfo (so maybe reporting it there will help more if it's not already reported).

However as a workaround using the flag `--term xterm` has worked for me.

**Comment by jwilm** [comment]
Have either of you done a `cargo update` which would result in a newer version of the `terminfo` crate being used?

**Comment by chrisduerr** [comment]
Neither `cargo update` nor bumping it to `0.5` worked for me.
